//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmClientKLAGUZ.TankServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tank", Namespace="http://schemas.datacontract.org/2004/07/ModelsKLAGUZ")]
    [System.SerializableAttribute()]
    public partial class Tank : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Power {
            get {
                return this.PowerField;
            }
            set {
                if ((this.PowerField.Equals(value) != true)) {
                    this.PowerField = value;
                    this.RaisePropertyChanged("Power");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Shield {
            get {
                return this.ShieldField;
            }
            set {
                if ((this.ShieldField.Equals(value) != true)) {
                    this.ShieldField = value;
                    this.RaisePropertyChanged("Shield");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TankServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTank", ReplyAction="http://tempuri.org/IService1/GetTankResponse")]
        ArmClientKLAGUZ.TankServiceReference.Tank GetTank(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTank", ReplyAction="http://tempuri.org/IService1/GetTankResponse")]
        System.Threading.Tasks.Task<ArmClientKLAGUZ.TankServiceReference.Tank> GetTankAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTank", ReplyAction="http://tempuri.org/IService1/CreateTankResponse")]
        string CreateTank(ArmClientKLAGUZ.TankServiceReference.Tank tank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTank", ReplyAction="http://tempuri.org/IService1/CreateTankResponse")]
        System.Threading.Tasks.Task<string> CreateTankAsync(ArmClientKLAGUZ.TankServiceReference.Tank tank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTanks", ReplyAction="http://tempuri.org/IService1/GetAllTanksResponse")]
        ArmClientKLAGUZ.TankServiceReference.Tank[] GetAllTanks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTanks", ReplyAction="http://tempuri.org/IService1/GetAllTanksResponse")]
        System.Threading.Tasks.Task<ArmClientKLAGUZ.TankServiceReference.Tank[]> GetAllTanksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ArmClientKLAGUZ.TankServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ArmClientKLAGUZ.TankServiceReference.IService1>, ArmClientKLAGUZ.TankServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArmClientKLAGUZ.TankServiceReference.Tank GetTank(string name) {
            return base.Channel.GetTank(name);
        }
        
        public System.Threading.Tasks.Task<ArmClientKLAGUZ.TankServiceReference.Tank> GetTankAsync(string name) {
            return base.Channel.GetTankAsync(name);
        }
        
        public string CreateTank(ArmClientKLAGUZ.TankServiceReference.Tank tank) {
            return base.Channel.CreateTank(tank);
        }
        
        public System.Threading.Tasks.Task<string> CreateTankAsync(ArmClientKLAGUZ.TankServiceReference.Tank tank) {
            return base.Channel.CreateTankAsync(tank);
        }
        
        public ArmClientKLAGUZ.TankServiceReference.Tank[] GetAllTanks() {
            return base.Channel.GetAllTanks();
        }
        
        public System.Threading.Tasks.Task<ArmClientKLAGUZ.TankServiceReference.Tank[]> GetAllTanksAsync() {
            return base.Channel.GetAllTanksAsync();
        }
    }
}
